### ISSUE TITLE
Internal compiler error (CompilerDiagnostics.accumulateErrorsThen)

### ISSUE THREAD

**Issue by toddATavail** [AvailLang/Avail#126]
I received this failure, which is difficult to catch but reliably hangs the workbench:

```
Unexpected internal failure in AvailTask:
java.lang.AssertionError
	at com.avail.compiler.problems.CompilerDiagnostics.accumulateErrorsThen(CompilerDiagnostics.java:523)
	at com.avail.compiler.problems.CompilerDiagnostics.reportError(CompilerDiagnostics.java:490)
	at com.avail.compiler.problems.CompilerDiagnostics.reportError(CompilerDiagnostics.java:471)
	at com.avail.compiler.AvailCompiler.lambda$tryIfUnambiguousThen$2(AvailCompiler.java:533)
	at com.avail.compiler.CompilationContext.lambda$setNoMoreWorkUnits$0(CompilationContext.java:260)
	at com.avail.compiler.CompilationContext.lambda$workUnitCompletion$2(CompilationContext.java:482)
	at com.avail.compiler.CompilationContext.lambda$workUnitsDo$3(CompilationContext.java:530)
	at com.avail.AvailTask.run(AvailTask.java:258)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I do not know the cause of this error yet, and I am not sure that it is always the cause of the hangs that I have been experiencing — it took me a while to catch it even once. The workbench often hangs during Avail development without reporting an internal error to the transcript.

I will try to work around the issue for now.

**Comment by markATavail** [comment]
Fixed the crashes.  Also added prioritized parse rejections.  Also now reports ambiguous parses in differing ways, depending on whether the pre-macro or post-macro phrases (or neither) differ between the two parses.
