### ISSUE TITLE
L2 optimization error

### ISSUE THREAD

**Issue by toddATavail** [AvailLang/Avail#132]
I am afraid that I don't have any real context for this. I was working on a module for a client. I had been developing the module iteratively for several hours, and I got this part way through compilation (5,654 /  8,621). I will try to determine if it is trivially reproducible, and update this issue when I discover that.

```
Unexpected internal failure in AvailTask:
java.lang.AssertionError
	at com.avail.optimizer.L2ValueManifest.recordDefinition(L2ValueManifest.java:599)
	at com.avail.interpreter.levelTwo.operand.L2WriteOperand.instructionWasAdded(L2WriteOperand.java:194)
	at com.avail.interpreter.levelTwo.operation.L2_PHI_PSEUDO_OPERATION.instructionWasAdded(L2_PHI_PSEUDO_OPERATION.java:204)
	at com.avail.interpreter.levelTwo.L2Instruction.justAdded(L2Instruction.java:333)
	at com.avail.optimizer.L2BasicBlock.addInstruction(L2BasicBlock.java:390)
	at com.avail.optimizer.L2Generator.addInstruction(L2Generator.java:942)
	at com.avail.optimizer.L2ValueManifest.generatePhi(L2ValueManifest.java:990)
	at com.avail.optimizer.L2ValueManifest.lambda$populateFromIntersection$20(L2ValueManifest.java:885)
	at java.util.HashMap$Values.forEach(HashMap.java:981)
	at com.avail.optimizer.L2ValueManifest.populateFromIntersection(L2ValueManifest.java:848)
	at com.avail.optimizer.L2BasicBlock.startIn(L2BasicBlock.java:369)
	at com.avail.optimizer.L2Generator.startBlock(L2Generator.java:889)
	at com.avail.optimizer.L1Translator.generateCall(L1Translator.java:1240)
	at com.avail.optimizer.L1Translator.L1_doCall(L1Translator.java:3110)
	at com.avail.interpreter.levelOne.L1Operation$1.dispatch(L1Operation.java:76)
	at com.avail.optimizer.L1Translator.translateL1Instructions(L1Translator.java:2903)
	at com.avail.optimizer.L1Translator.translate(L1Translator.java:3088)
	at com.avail.optimizer.L1Translator.translateToLevelTwo(L1Translator.java:3060)
	at com.avail.interpreter.levelTwo.operation.L2_DECREMENT_COUNTER_AND_REOPTIMIZE_ON_ZERO.lambda$decrement$0(L2_DECREMENT_COUNTER_AND_REOPTIMIZE_ON_ZERO.java:111)
	at com.avail.descriptor.CompiledCodeDescriptor.o_DecrementCountdownToReoptimize(CompiledCodeDescriptor.java:813)
	at com.avail.descriptor.AvailObject.decrementCountdownToReoptimize(AvailObject.java:2120)
	at com.avail.interpreter.levelTwo.operation.L2_DECREMENT_COUNTER_AND_REOPTIMIZE_ON_ZERO.decrement(L2_DECREMENT_COUNTER_AND_REOPTIMIZE_ON_ZERO.java:105)
	at com.avail.optimizer.jvm.generated.JVMChunk_88c6d35c_c257_4dc3_8654_bcae35bf964c.runChunk(Unknown Source)
	at com.avail.interpreter.levelTwo.L2Chunk.runChunk(L2Chunk.java:800)
	at com.avail.interpreter.Interpreter.runChunk(Interpreter.java:2246)
	at com.avail.interpreter.Interpreter.invokeFunction(Interpreter.java:2124)
	at com.avail.interpreter.levelTwo.L1InstructionStepper.callMethodAfterLookup(L1InstructionStepper.java:928)
	at com.avail.interpreter.levelTwo.L1InstructionStepper.run(L1InstructionStepper.java:297)
	at com.avail.optimizer.jvm.generated.JVMChunk_88c6d35c_c257_4dc3_8654_bcae35bf964c.runChunk(Unknown Source)
	at com.avail.interpreter.levelTwo.L2Chunk.runChunk(L2Chunk.java:800)
	at com.avail.interpreter.Interpreter.runChunk(Interpreter.java:2246)
	at com.avail.interpreter.Interpreter.run(Interpreter.java:2155)
	at com.avail.interpreter.Interpreter.lambda$executeFiber$17(Interpreter.java:2390)
	at com.avail.AvailTask.lambda$forFiberResumption$2(AvailTask.java:143)
	at com.avail.AvailRuntime.lambda$whenLevelOneUnsafeDo$3(AvailRuntime.java:1572)
	at com.avail.AvailTask.run(AvailTask.java:254)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by toddATavail** [comment]
I can't immediately reproduce this, probably because I need to do more L2 optimization in order to catch it.

**Comment by markATavail** [comment]
Fixed, added regression test.  Pushed to 1.4.0 and development.
