### ISSUE TITLE
Cancel button doesn’t work in entry point selector

### ISSUE THREAD

**Issue by tdhsmith** [AvailLang/Avail#158]
If your command is ambiguous and you hit “cancel” in the subsequent entry point selector dialog, you get:
```
Internal error: null cannot be cast to non-null type com.avail.builder.AvailBuilder.CompiledCommand
kotlin.TypeCastException: null cannot be cast to non-null type com.avail.builder.AvailBuilder.CompiledCommand
	at com.avail.environment.actions.SubmitInputAction$actionPerformed$1.invoke(SubmitInputAction.kt:104)
	at com.avail.environment.actions.SubmitInputAction$actionPerformed$1.invoke(SubmitInputAction.kt:59)
	at com.avail.builder.AvailBuilder.processParsedCommand(AvailBuilder.kt:1133)
	at com.avail.builder.AvailBuilder.access$processParsedCommand(AvailBuilder.kt:108)
	at com.avail.builder.AvailBuilder$scheduleAttemptCommand$decrement$1.invoke(AvailBuilder.kt:863)
	at com.avail.builder.AvailBuilder$scheduleAttemptCommand$decrement$1.invoke(AvailBuilder.kt:108)
	at com.avail.builder.AvailBuilder$scheduleAttemptCommand$1.invoke(AvailBuilder.kt:955)
	at com.avail.builder.AvailBuilder$scheduleAttemptCommand$1.invoke(AvailBuilder.kt:108)
	at com.avail.compiler.AvailCompiler$parseCommand$2.invoke(AvailCompiler.kt:3569)
	at com.avail.compiler.AvailCompiler$parseCommand$2.invoke(AvailCompiler.kt:199)
	at com.avail.compiler.CompilationContext$noMoreWorkUnits$3.invoke(CompilationContext.kt:203)
	at com.avail.compiler.CompilationContext$noMoreWorkUnits$3.invoke(CompilationContext.kt:126)
	at com.avail.compiler.CompilationContext$workUnitCompletion$1.invoke(CompilationContext.kt:439)
	at com.avail.compiler.CompilationContext$workUnitCompletion$1.invoke(CompilationContext.kt:126)
	at com.avail.compiler.CompilationContext$workUnitsDo$1.value(CompilationContext.kt:489)
	at com.avail.AvailTask.run(AvailTask.java:259)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
I'd wager a guess this is a regression caused by moving to Kotlin's stricter nullness handling.

**Comment by tdhsmith** [comment]
I'll attempt to untangle this myself, presumably just making an argument nullable or adding a conditional, but wanted to document it here in case I get lost in the weeds of verifying my change is logically sound.

**Comment by toddATavail** [comment]
I wrote a response to this on April 1, but it bounced, so here it is again via the web form:

----------------------------------------

I agree with your analysis. By all means, if you have the bandwidth,
please attempt a fix and issue a merge request to `development`.

**Comment by markATavail** [comment]
I bumped into this and went ahead and fixed it in the descriptor_breakup branch.  That'll be merged to development in the next month or two.

**Comment by tdhsmith** [comment]
Thanks. At some point my one clean test case stopped working and it was taking more effort to create a new ambiguity than I expected.

**Comment by markATavail** [comment]
Long since merged, so closing.  Note that an ambiguity within the same module is still not presented well.
