### ISSUE TITLE
Avail scanner attempted to read past end of file

### ISSUE THREAD

**Issue by toddATavail** [AvailLang/Avail#17]
**Reported by todd on 29 Nov 2012 00:02 UTC**
When I attempted to compile "AnnalsObjects" in the "annals" root, I received this stack trace: 

com.avail.compiler.scanning.AvailScannerException: null: Attempted to read past end of file
	at com.avail.compiler.scanning.AvailScanner.next(AvailScanner.java:208)
	at com.avail.compiler.scanning.AvailScanner.scanString(AvailScanner.java:859)
	at com.avail.compiler.AbstractAvailCompiler.tokenize(AbstractAvailCompiler.java:1404)
	at com.avail.compiler.AbstractAvailCompiler.create(AbstractAvailCompiler.java:596)
	at com.avail.builder.AvailBuilder.traceModuleImports(AvailBuilder.java:213)
	at com.avail.builder.AvailBuilder.buildTarget(AvailBuilder.java:435)
	at com.avail.builder.AvailBuilder$1.run(AvailBuilder.java:350)
	at java.lang.Thread.run(Thread.java:680)
	at com.avail.builder.AvailBuilder.buildTargetInNewAvailThread(AvailBuilder.java:374)
	at com.avail.environment.AvailBuilderFrame$BuildTask.doInBackground(AvailBuilderFrame.java:383)
	at com.avail.environment.AvailBuilderFrame$BuildTask.doInBackground(AvailBuilderFrame.java:1)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at javax.swing.SwingWorker.run(SwingWorker.java:316)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)

**Comment by toddATavail** [comment]
**Comment by mark on 21 Mar 2013 19:37 UTC**
It now indicates at the first token "Expected... Module keyword".

**Comment by toddATavail** [comment]
**Modified by mark on 21 Mar 2013 19:39 UTC**

**Comment by toddATavail** [comment]
**Comment by todd on 6 Apr 2014 14:44 UTC**
Milestone Release 1.0.0 deleted
