### ISSUE TITLE
Recompile on Avail Workbench

### ISSUE THREAD

**Issue by toddATavail** [AvailLang/Avail#33]
**Reported by rich on 6 Apr 2014 22:01 UTC**
Had repositories populated.  Opened Workbench, generated documentation, but did not load repositories.  Made changes to an Avail module, UTF-8 Codec.avail.  Saved changes.  Went back to workbench and double clicked on Avail to recompile.  Obtained the following error:

Exception in thread "Thread-8" Exception in thread "Thread-7" java.lang.AssertionError
	at com.avail.builder.AvailBuilder$BuildUnloader$1$1.value(AvailBuilder.java:846)
	at com.avail.AvailTask.run(AvailTask.java:248)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Exception in thread "Thread-6" java.lang.AssertionError
	at com.avail.builder.AvailBuilder$BuildUnloader$1$1.value(AvailBuilder.java:846)
	at com.avail.AvailTask.run(AvailTask.java:248)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
java.lang.AssertionError
	at com.avail.builder.AvailBuilder$BuildUnloader$1$1.value(AvailBuilder.java:846)
	at com.avail.AvailTask.run(AvailTask.java:248)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

**Comment by toddATavail** [comment]
**Comment by rich on 6 Apr 2014 22:30 UTC**
I believe the following is happening:
    Generating documentation without loading puts the workbench in state where it believes all Avail is loaded from the repository, but it is not.  So when making a change to a module then attempting to build, the workbench thinks that it must first unload, though, there is nothing there to unload.

Repeatable steps:
  1) Open workbench and build Avail library.
  2) Close workbench.
  3) Open new workbench
  4) Generate Stacks documentation
  5) Go into module in path of documentation and make a change.  Save change to module.
  6) From open workbench, double click on Avail to rebuild Avail.

**Comment by toddATavail** [comment]
**Comment by mark on 10 Apr 2014 18:23 UTC**
Rich, I just pushed a fix for #41.  If it works for you, please mark this item as completed.

**Comment by toddATavail** [comment]
**Comment by todd on 20 Apr 2014 22:32 UTC**
This is finished, now right? If so, then please close it.

**Comment by toddATavail** [comment]
**Modified by rich on 21 Apr 2014 03:21 UTC**
