### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: java.lang.Ill egalArgumentException: Width (-1) and height (0) must be non-zero

### ISSUE THREAD

**Issue by toddATavail** [AvailLang/Avail#40]
**Reported by anonymous on 18 Apr 2014 15:23 UTC**
Spencer here: trying to run Avail on Windows. Todd thinks this is related to a bad preference file.

Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: java.lang.Ill
egalArgumentException: Width (-1) and height (0) must be non-zero
        at com.avail.utility.LRUCache$ValueFuture.get(LRUCache.java:470)
        at com.avail.utility.LRUCache.get(LRUCache.java:790)
        at com.avail.environment.nodes.AbstractBuilderFrameTreeNode.icon(Abstrac
tBuilderFrameTreeNode.java:153)
        at com.avail.environment.AvailWorkbench$3.getTreeCellRendererComponent(A
vailWorkbench.java:2292)
        at javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimen
sions(BasicTreeUI.java:2809)
        at javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayout
Cache.java:492)
        at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePrefer
redSize(VariableHeightLayoutCache.java:1359)
        at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(Varia
bleHeightLayoutCache.java:1495)
        at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(Varia
bleHeightLayoutCache.java:1287)
        at javax.swing.tree.VariableHeightLayoutCache.ensurePathIsExpanded(Varia
bleHeightLayoutCache.java:983)
        at javax.swing.tree.VariableHeightLayoutCache.setExpandedState(VariableH
eightLayoutCache.java:181)
        at javax.swing.plaf.basic.BasicTreeUI.updateExpandedDescendants(BasicTre
eUI.java:1695)
        at javax.swing.plaf.basic.BasicTreeUI$Handler.treeExpanded(BasicTreeUI.j
ava:3808)
        at javax.swing.JTree.fireTreeExpanded(JTree.java:2756)
        at javax.swing.JTree.setExpandedState(JTree.java:3616)
        at javax.swing.JTree.expandPath(JTree.java:2204)
        at javax.swing.JTree.expandRow(JTree.java:2219)
        at com.avail.environment.AvailWorkbench.<init>(AvailWorkbench.java:2462)

        at com.avail.environment.AvailWorkbench$10.run(AvailWorkbench.java:2795)

        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
        at java.awt.EventQueue.access$200(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:694)
        at java.awt.EventQueue$3.run(EventQueue.java:692)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDo
main.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThre
ad.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.
java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThre
ad.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)

        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)

        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.lang.IllegalArgumentException: Width (-1) and height (0) must be
 non-zero
        at java.awt.image.ReplicateScaleFilter.<init>(ReplicateScaleFilter.java:
102)
        at java.awt.image.AreaAveragingScaleFilter.<init>(AreaAveragingScaleFilt
er.java:77)
        at java.awt.Image.getScaledInstance(Image.java:171)
        at com.avail.environment.nodes.AbstractBuilderFrameTreeNode$1.value(Abst
ractBuilderFrameTreeNode.java:129)
        at com.avail.environment.nodes.AbstractBuilderFrameTreeNode$1.value(Abst
ractBuilderFrameTreeNode.java:120)
        at com.avail.utility.LRUCache.get(LRUCache.java:758)
        ... 31 more

**Comment by toddATavail** [comment]
**Comment by mark on 18 Apr 2014 23:27 UTC**
It looks like you're running an older version of the code, since it refers to line numbers that are out of range.  But it looks like the proximal cause is that it couldn't locate some required graphical resource in /distro/images, most likely the package and module icons used by the workbench.

**Comment by toddATavail** [comment]
**Comment by Spencer on 19 Apr 2014 21:43 UTC**
Started a Windows 7 VM and built Avail. I just attached the Java exception I get which looks to be the same issue still. I did not use the installer, but followed the build process with git and ant on the VM.

**Comment by toddATavail** [comment]
**Modified by todd on 24 Apr 2014 05:18 UTC**
