### ISSUE TITLE
Avail Workbench doesn't start

### ISSUE THREAD

**Issue by toddATavail** [AvailLang/Avail#45]
**Reported by todd on 21 Apr 2014 16:28 UTC**
I just did a completely clean uninstall, clean, pull, ant. When I launch avail-dev (on Mac OS X 10.9.x), I get this:

Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: java.lang.NullPointerException
	at com.avail.utility.LRUCache$ValueFuture.get(LRUCache.java:470)
	at com.avail.utility.LRUCache.get(LRUCache.java:790)
	at com.avail.environment.nodes.AbstractBuilderFrameTreeNode.icon(AbstractBuilderFrameTreeNode.java:155)
	at com.avail.environment.AvailWorkbench$3.getTreeCellRendererComponent(AvailWorkbench.java:1478)
	at javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:2809)
	at javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:492)
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1359)
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1495)
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1287)
	at javax.swing.tree.VariableHeightLayoutCache.ensurePathIsExpanded(VariableHeightLayoutCache.java:983)
	at javax.swing.tree.VariableHeightLayoutCache.setExpandedState(VariableHeightLayoutCache.java:181)
	at javax.swing.plaf.basic.BasicTreeUI.updateExpandedDescendants(BasicTreeUI.java:1695)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.treeExpanded(BasicTreeUI.java:3808)
	at javax.swing.JTree.fireTreeExpanded(JTree.java:2756)
	at javax.swing.JTree.setExpandedState(JTree.java:3616)
	at javax.swing.JTree.expandPath(JTree.java:2204)
	at javax.swing.JTree.expandRow(JTree.java:2219)
	at com.avail.environment.AvailWorkbench.<init>(AvailWorkbench.java:1646)
	at com.avail.environment.AvailWorkbench$12.run(AvailWorkbench.java:2034)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.lang.NullPointerException
	at javax.swing.ImageIcon.<init>(ImageIcon.java:205)
	at com.avail.environment.nodes.AbstractBuilderFrameTreeNode$1.value(AbstractBuilderFrameTreeNode.java:127)
	at com.avail.environment.nodes.AbstractBuilderFrameTreeNode$1.value(AbstractBuilderFrameTreeNode.java:120)
	at com.avail.utility.LRUCache.get(LRUCache.java:758)
	... 31 more

**Comment by toddATavail** [comment]
**Comment by todd on 22 Apr 2014 01:00 UTC**
This is resolved in master.
