### ISSUE TITLE
Set addition failure during semantic restriction definition

### ISSUE THREAD

**Issue by toddATavail** [AvailLang/Avail#46]
**Reported by todd on 23 Apr 2014 04:41 UTC**
In a module not yet checked in, I was adding a semantic restriction to "Public stable abstract method_is_". The decompile of the method is:

Shared function with code: [: (string)'s type, arg2 : ([](arg1))'s type |
			Require : arg1 is canonical;
			Require : arg1 is unambiguous;
			
		]

There is a single existing definition of "Public stable abstract method_is_":

[stable abstract method_is_"}, <a MethodDefinition
		DEFINITION_METHOD = 1 definition of $"Public stable abstract method_is_" (from Definers)
		MODULE = Module: "/avail/Avail/Foundation/Definers"
		BODY_BLOCK = Shared function with code: [arg1 : string, arg2 : ([]({bundle"Public))'s type |
					Abstract method arg1 is arg2;
					Method arg1 is stable at arg2;
				]>, raw pojo: #1  string: known=[any](any,)
	# 2  ([type: known=[string, any](])'s)
		Success: <string, ([type|2>
		Failure: (0 solutions)
	Failure: (0 solutions), {a SemanticRestriction
		FUNCTION = Shared function with code: [arg1 : (string)'s type, arg2 : (([](])'s))'s type)'s type |
					Require : arg1 is public;
					Require : message arg1 does not specify lexical groups;
					If | arg2 | = 1 then [: ([](
								local1))'s type;
								local1 := Cast|cast arg2 ' s instances  tuple [ 1 ] into [: *** DEPTH *** |
												arg3
											](arg3);
								Require : local1 ' s parameters are not metatypes or function types;
							];
					
				]
		DEFINITION_METHOD = 1 definition of $"Public stable abstract method_is_" (from Definers)
		DEFINITION_MODULE = Module: "/avail/Avail/Foundation/Definers", a SemanticRestriction
		FUNCTION = Shared function with code: [: (string)'s type, arg2 : ([](arg1))'s type |
					Require : arg1 is canonical;
					Require : arg1 is unambiguous;
					
				]
		DEFINITION_METHOD = 1 definition of $"Public stable abstract method_is_" (from Definers)
		DEFINITION_MODULE = Module: "/avail/Avail/Foundation/Late Definers", a SemanticRestriction
		FUNCTION = Shared function with code: [: (string)'s type, arg2 : ([](arg1))'s type |
					Require : arg1 is canonical;
					Require : arg1 is unambiguous;
					
				]
		DEFINITION_METHOD = 1 definition of $"Public stable abstract method_is_" (from Definers)
		DEFINITION_MODULE = Module: "/avail/Avail/Foundation/Late Definers"}, <>, nil]

Without further ado, here's the exception:

[EXECUTION]: module "/avail/Avail/Foundation/Late Definers", line 133:
Execution error: 8
java.lang.ArrayIndexOutOfBoundsException: 8
	at com.avail.descriptor.LinearSetBinDescriptor.emptyBinForLevel(LinearSetBinDescriptor.java:527)
	at com.avail.descriptor.LinearSetBinDescriptor.o_SetBinAddingElementHashLevelCanDestroy(LinearSetBinDescriptor.java:190)
	at com.avail.descriptor.AvailObject.setBinAddingElementHashLevelCanDestroy(AvailObject.java:730)
	at com.avail.descriptor.HashedSetBinDescriptor.o_SetBinAddingElementHashLevelCanDestroy(HashedSetBinDescriptor.java:231)
	at com.avail.descriptor.AvailObject.setBinAddingElementHashLevelCanDestroy(AvailObject.java:730)
	at com.avail.descriptor.LinearSetBinDescriptor.o_SetBinAddingElementHashLevelCanDestroy(LinearSetBinDescriptor.java:168)
	at com.avail.descriptor.AvailObject.setBinAddingElementHashLevelCanDestroy(AvailObject.java:730)
	at com.avail.descriptor.HashedSetBinDescriptor.o_SetBinAddingElementHashLevelCanDestroy(HashedSetBinDescriptor.java:231)
	at com.avail.descriptor.AvailObject.setBinAddingElementHashLevelCanDestroy(AvailObject.java:730)
	at com.avail.descriptor.LinearSetBinDescriptor.o_SetBinAddingElementHashLevelCanDestroy(LinearSetBinDescriptor.java:168)
	at com.avail.descriptor.AvailObject.setBinAddingElementHashLevelCanDestroy(AvailObject.java:730)
	at com.avail.descriptor.HashedSetBinDescriptor.o_SetBinAddingElementHashLevelCanDestroy(HashedSetBinDescriptor.java:231)
	at com.avail.descriptor.AvailObject.setBinAddingElementHashLevelCanDestroy(AvailObject.java:730)
	at com.avail.descriptor.LinearSetBinDescriptor.o_SetBinAddingElementHashLevelCanDestroy(LinearSetBinDescriptor.java:168)
	at com.avail.descriptor.AvailObject.setBinAddingElementHashLevelCanDestroy(AvailObject.java:730)
	at com.avail.descriptor.HashedSetBinDescriptor.o_SetBinAddingElementHashLevelCanDestroy(HashedSetBinDescriptor.java:231)
	at com.avail.descriptor.AvailObject.setBinAddingElementHashLevelCanDestroy(AvailObject.java:730)
	at com.avail.descriptor.LinearSetBinDescriptor.o_SetBinAddingElementHashLevelCanDestroy(LinearSetBinDescriptor.java:168)
	at com.avail.descriptor.AvailObject.setBinAddingElementHashLevelCanDestroy(AvailObject.java:730)
	at com.avail.descriptor.HashedSetBinDescriptor.o_SetBinAddingElementHashLevelCanDestroy(HashedSetBinDescriptor.java:231)
	at com.avail.descriptor.AvailObject.setBinAddingElementHashLevelCanDestroy(AvailObject.java:730)
	at com.avail.descriptor.LinearSetBinDescriptor.o_SetBinAddingElementHashLevelCanDestroy(LinearSetBinDescriptor.java:168)
	at com.avail.descriptor.AvailObject.setBinAddingElementHashLevelCanDestroy(AvailObject.java:730)
	at com.avail.descriptor.HashedSetBinDescriptor.o_SetBinAddingElementHashLevelCanDestroy(HashedSetBinDescriptor.java:231)
	at com.avail.descriptor.AvailObject.setBinAddingElementHashLevelCanDestroy(AvailObject.java:730)
	at com.avail.descriptor.LinearSetBinDescriptor.o_SetBinAddingElementHashLevelCanDestroy(LinearSetBinDescriptor.java:168)
	at com.avail.descriptor.AvailObject.setBinAddingElementHashLevelCanDestroy(AvailObject.java:730)
	at com.avail.descriptor.HashedSetBinDescriptor.o_SetBinAddingElementHashLevelCanDestroy(HashedSetBinDescriptor.java:231)
	at com.avail.descriptor.AvailObject.setBinAddingElementHashLevelCanDestroy(AvailObject.java:730)
	at com.avail.descriptor.SetDescriptor.o_SetWithElementCanDestroy(SetDescriptor.java:423)
	at com.avail.descriptor.AvailObject.setWithElementCanDestroy(AvailObject.java:3720)
	at com.avail.descriptor.ModuleDescriptor.o_ModuleAddSemanticRestriction(ModuleDescriptor.java:503)
	at com.avail.descriptor.AvailObject.moduleAddSemanticRestriction(AvailObject.java:5126)
	at com.avail.interpreter.AvailLoader$5.value(AvailLoader.java:574)
	at com.avail.descriptor.Descriptor.o_Lock(Descriptor.java:3828)
	at com.avail.descriptor.AvailObject.lock(AvailObject.java:6240)
	at com.avail.interpreter.AvailLoader.addSemanticRestriction(AvailLoader.java:569)
	at com.avail.interpreter.primitive.P_248_AddSemanticRestriction.attempt(P_248_AddSemanticRestriction.java:90)
	at com.avail.interpreter.Interpreter.attemptPrimitive(Interpreter.java:940)
	at com.avail.interpreter.Interpreter.invokePossiblePrimitiveWithReifiedCaller(Interpreter.java:1731)
	at com.avail.interpreter.levelTwo.operation.L2_INVOKE.step(L2_INVOKE.java:91)
	at com.avail.interpreter.Interpreter.run(Interpreter.java:1826)
	at com.avail.interpreter.Interpreter$6.value(Interpreter.java:1878)
	at com.avail.interpreter.Interpreter$6.value(Interpreter.java:1)
	at com.avail.AvailTask$1.value(AvailTask.java:111)
	at com.avail.AvailTask.run(AvailTask.java:247)
	at com.avail.AvailRuntime$3.value(AvailRuntime.java:1588)
	at com.avail.AvailTask.run(AvailTask.java:247)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

This is basically standing in the way of making incorrect method definition (because of non-canonical names or ambiguous lookups) more user-friendly.

**Comment by toddATavail** [comment]
**Comment by todd on 23 Apr 2014 05:02 UTC**
I committed and pushed my work. "Late Definers" is a new module in /avail/Avail/Foundation. There is a commented out section of code near the bottom. You can uncomment this code to cause the exception described above. Please leave the code uncommented when the issue is resolved.

**Comment by toddATavail** [comment]
**Modified by mark on 24 Apr 2014 00:21 UTC**
