### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Node name 0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080; too long

### ISSUE THREAD

**Issue by toddATavail** [AvailLang/Avail#47]
**Reported by spencer on 23 Apr 2014 04:53 UTC**
Spencer here: tried to install on Unix Fedora 20 x86_64
[spencer](root@localhost)# ant -version
Apache Ant(TM) version 1.9.2 compiled on September 12 2013
[spencer](root@localhost)# java -version
java version "1.7.0_55"
OpenJDK Runtime Environment (fedora-2.4.7.0.fc20-x86_64 u55-b13)
OpenJDK 64-Bit Server VM (build 24.51-b03, mixed mode)

Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Node name 0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080;0,0,1920,1080; too long
	at java.util.prefs.AbstractPreferences.node(AbstractPreferences.java:829)
	at java.util.prefs.AbstractPreferences.node(AbstractPreferences.java:841)
	at java.util.prefs.AbstractPreferences.node(AbstractPreferences.java:811)
	at com.avail.environment.AvailWorkbench.placementPreferencesNodeForRectangles(AvailWorkbench.java:1272)
	at com.avail.environment.AvailWorkbench.getInitialConfiguration(AvailWorkbench.java:1444)
	at com.avail.environment.AvailWorkbench.<init>(AvailWorkbench.java:1520)
	at com.avail.environment.AvailWorkbench$12.run(AvailWorkbench.java:2034)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by toddATavail** [comment]
**Comment by Spener: spencer@availlang.org on 23 Apr 2014 04:54 UTC**
Unsure if this is related to bug #48

**Comment by toddATavail** [comment]
**Modified by spencer on 23 Apr 2014 05:52 UTC**

**Comment by toddATavail** [comment]
**Comment by mark on 24 Apr 2014 05:06 UTC**
Java's GraphicsDevice.getScreenDevices() was lying (or the documentation was unclear) and saying there were 120 monitors connected, so we now associate saved workbench position with the list of monitor id strings (getIDstring()).
