### ISSUE TITLE
Generating documentation always causes FileNotFoundException

### ISSUE THREAD

**Issue by toddATavail** [AvailLang/Avail#57]
**Reported by bert barabas on 28 Apr 2014 22:36 UTC**
Here is the stack trace:

java.io.FileNotFoundException: src\com\avail\stacks\configuration\implementation wrapper.html.template (The system cannot find the path specified)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:131)
	at java.io.FileInputStream.<init>(FileInputStream.java:87)
	at com.avail.stacks.HTMLBuilder.getOuterHTMLTemplate(HTMLBuilder.java:166)
	at com.avail.stacks.StacksCommentsModule.writeAmbiguousAliasHTMLFiles(StacksCommentsModule.java:1366)
	at com.avail.stacks.StacksCommentsModule.calculateFinalImplementationGroupsMap(StacksCommentsModule.java:1107)
	at com.avail.stacks.StacksGenerator.generate(StacksGenerator.java:237)
	at com.avail.builder.AvailBuilder$DocumentationTracer.generate(AvailBuilder.java:2251)
	at com.avail.builder.AvailBuilder.generateDocumentation(AvailBuilder.java:2799)
	at com.avail.environment.tasks.DocumentationTask.executeTask(DocumentationTask.java:55)
	at com.avail.environment.AvailWorkbench$AbstractWorkbenchTask.doInBackground(AvailWorkbench.java:245)
	at com.avail.environment.AvailWorkbench$AbstractWorkbenchTask.doInBackground(AvailWorkbench.java:137)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by toddATavail** [comment]
**Modified by todd on 3 May 2014 02:59 UTC**

**Comment by toddATavail** [comment]
**Modified by todd on 30 May 2014 01:55 UTC**
