### ISSUE TITLE
Stacks NullPointerException when generating after compiling all modules

### ISSUE THREAD

**Issue by toddATavail** [AvailLang/Avail#89]
**Reported by rich on 8 Mar 2015 13:23 UTC**
Compiling all modules in avail and then running generate stacks documentation on Avail.avail causes the following error.

Exception in thread "AvailThread-1" java.lang.NullPointerException
	at com.avail.stacks.StacksExtendsModule.renameImplementation(StacksExtendsModule.java:214)
	at com.avail.stacks.StacksCommentsModule.buildModuleImportMaps(StacksCommentsModule.java:491)
	at com.avail.stacks.StacksCommentsModule.<init>(StacksCommentsModule.java:349)
	at com.avail.stacks.StacksGenerator.add(StacksGenerator.java:163)
	at com.avail.builder.AvailBuilder$DocumentationTracer.loadComments(AvailBuilder.java:2286)
	at com.avail.builder.AvailBuilder$DocumentationTracer$4.value(AvailBuilder.java:2324)
	at com.avail.AvailTask.run(AvailTask.java:247)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by toddATavail** [comment]
**Modified by rich on 8 Mar 2015 13:26 UTC**
